# =============================================================
#  PC 2 — Brokers de Base (Norte, Sul, Leste, Oeste)
#  Rodar com: docker compose -f docker-compose.bases.yml up
# =============================================================

services:
  base_norte:
    build:
      context: ..
      dockerfile: base/dockerfile
    container_name: base_norte
    restart: unless-stopped
    ports:
      - "${PORTA_BASE_NORTE}:${PORTA_BASE_NORTE}"
      - "${PORTA_BASE_NORTE_UDP}:${PORTA_BASE_NORTE_UDP}/udp"
    environment:
      BASE_ID: "NORTE"
      MINHA_PORTA: "${PORTA_BASE_NORTE}"
      MINHA_PORTA_UDP: "${PORTA_BASE_NORTE_UDP}"
      IP_MONITOR: "${IP_MONITOR}"
      IP_BASE_NORTE: "base_norte"
      IP_BASE_SUL: "base_sul"
      IP_BASE_LESTE: "base_leste"
      IP_BASE_OESTE: "base_oeste"
      PORTA_BASE_NORTE: "${PORTA_BASE_NORTE}"
      PORTA_BASE_SUL: "${PORTA_BASE_SUL}"
      PORTA_BASE_LESTE: "${PORTA_BASE_LESTE}"
      PORTA_BASE_OESTE: "${PORTA_BASE_OESTE}"
      IP_PC_DRONES: "${IP_PC_DRONES}"
      FABRIC_ORG_DOMAIN: "norte.ormuz.com"
      FABRIC_USER: "Admin"
      # NOVA LISTA DE PEERS PARA ENDOSSO (Norte pede a todos)
      FABRIC_PEERS: "peer0.norte.ormuz.com,peer0.sul.ormuz.com,peer0.leste.ormuz.com,peer0.oeste.ormuz.com"
    volumes:
      - ../fabric/crypto-config:/app/fabric/crypto-config:ro
    networks:
      - ormuz_net
      - ormuz_fabric

  base_sul:
    build:
      context: ..
      dockerfile: base/dockerfile
    container_name: base_sul
    restart: unless-stopped
    ports:
      - "${PORTA_BASE_SUL}:${PORTA_BASE_SUL}"
      - "${PORTA_BASE_SUL_UDP}:${PORTA_BASE_SUL_UDP}/udp"
    environment:
      BASE_ID: "SUL"
      MINHA_PORTA: "${PORTA_BASE_SUL}"
      MINHA_PORTA_UDP: "${PORTA_BASE_SUL_UDP}"
      IP_MONITOR: "${IP_MONITOR}"
      IP_BASE_NORTE: "base_norte"
      IP_BASE_SUL: "base_sul"
      IP_BASE_LESTE: "base_leste"
      IP_BASE_OESTE: "base_oeste"
      PORTA_BASE_NORTE: "${PORTA_BASE_NORTE}"
      PORTA_BASE_SUL: "${PORTA_BASE_SUL}"
      PORTA_BASE_LESTE: "${PORTA_BASE_LESTE}"
      PORTA_BASE_OESTE: "${PORTA_BASE_OESTE}"
      IP_PC_DRONES: "${IP_PC_DRONES}"
      FABRIC_ORG_DOMAIN: "sul.ormuz.com"
      FABRIC_USER: "Admin"
      # NOVA LISTA DE PEERS PARA ENDOSSO (Sul pede a todos)
      FABRIC_PEERS: "peer0.sul.ormuz.com,peer0.norte.ormuz.com,peer0.leste.ormuz.com,peer0.oeste.ormuz.com"
    volumes:
      - ../fabric/crypto-config:/app/fabric/crypto-config:ro
    networks:
      - ormuz_net
      - ormuz_fabric

  base_leste:
    build:
      context: ..
      dockerfile: base/dockerfile
    container_name: base_leste
    restart: unless-stopped
    ports:
      - "${PORTA_BASE_LESTE}:${PORTA_BASE_LESTE}"
      - "${PORTA_BASE_LESTE_UDP}:${PORTA_BASE_LESTE_UDP}/udp"
    environment:
      BASE_ID: "LESTE"
      MINHA_PORTA: "${PORTA_BASE_LESTE}"
      MINHA_PORTA_UDP: "${PORTA_BASE_LESTE_UDP}"
      IP_MONITOR: "${IP_MONITOR}"
      IP_BASE_NORTE: "base_norte"
      IP_BASE_SUL: "base_sul"
      IP_BASE_LESTE: "base_leste"
      IP_BASE_OESTE: "base_oeste"
      PORTA_BASE_NORTE: "${PORTA_BASE_NORTE}"
      PORTA_BASE_SUL: "${PORTA_BASE_SUL}"
      PORTA_BASE_LESTE: "${PORTA_BASE_LESTE}"
      PORTA_BASE_OESTE: "${PORTA_BASE_OESTE}"
      IP_PC_DRONES: "${IP_PC_DRONES}"
      FABRIC_ORG_DOMAIN: "leste.ormuz.com"
      FABRIC_USER: "Admin"
      # NOVA LISTA DE PEERS PARA ENDOSSO (Leste pede a todos)
      FABRIC_PEERS: "peer0.leste.ormuz.com,peer0.norte.ormuz.com,peer0.sul.ormuz.com,peer0.oeste.ormuz.com"
    volumes:
      - ../fabric/crypto-config:/app/fabric/crypto-config:ro
    networks:
      - ormuz_net
      - ormuz_fabric

  base_oeste:
    build:
      context: ..
      dockerfile: base/dockerfile
    container_name: base_oeste
    restart: unless-stopped
    ports:
      - "${PORTA_BASE_OESTE}:${PORTA_BASE_OESTE}"
      - "${PORTA_BASE_OESTE_UDP}:${PORTA_BASE_OESTE_UDP}/udp"
    environment:
      BASE_ID: "OESTE"
      MINHA_PORTA: "${PORTA_BASE_OESTE}"
      MINHA_PORTA_UDP: "${PORTA_BASE_OESTE_UDP}"
      IP_MONITOR: "${IP_MONITOR}"
      IP_BASE_NORTE: "base_norte"
      IP_BASE_SUL: "base_sul"
      IP_BASE_LESTE: "base_leste"
      IP_BASE_OESTE: "base_oeste"
      PORTA_BASE_NORTE: "${PORTA_BASE_NORTE}"
      PORTA_BASE_SUL: "${PORTA_BASE_SUL}"
      PORTA_BASE_LESTE: "${PORTA_BASE_LESTE}"
      PORTA_BASE_OESTE: "${PORTA_BASE_OESTE}"
      IP_PC_DRONES: "${IP_PC_DRONES}"
      FABRIC_ORG_DOMAIN: "oeste.ormuz.com"
      FABRIC_USER: "Admin"
      # NOVA LISTA DE PEERS PARA ENDOSSO (Oeste pede a todos)
      FABRIC_PEERS: "peer0.oeste.ormuz.com,peer0.norte.ormuz.com,peer0.sul.ormuz.com,peer0.leste.ormuz.com"
    volumes:
      - ../fabric/crypto-config:/app/fabric/crypto-config:ro
    networks:
      - ormuz_net
      - ormuz_fabric

networks:
  ormuz_net:
    driver: bridge
  ormuz_fabric:
    external: true