FROM python:3.11-slim

WORKDIR /app

# Instala a dependência que faltava para o Python conseguir falar com o Fabric
RUN pip install --no-cache-dir fabric-sdk-py

ENV PYTHONPATH="/app/shared"

COPY shared/ ./shared/
COPY config/ ./config/
COPY fabric/connection-profile.json ./fabric/connection-profile.json
COPY base/ ./base/

WORKDIR /app/base

EXPOSE 6001 6101/udp
CMD ["python", "broker.py"]