FROM python:3.11-slim

WORKDIR /app

# Instala a dependência que faltava para o Python conseguir falar com o Fabric
RUN pip install --no-cache-dir fabric-sdk-py

ENV PYTHONPATH="/app/shared"

COPY shared/ ./shared/
COPY config/ ./config/
COPY fabric/connection-profile.json ./fabric/connection-profile.json
COPY setor/ ./setor/

WORKDIR /app/setor

EXPOSE 5001-5008
CMD ["python", "broker_setor.py"]